version: 2.1
jobs:
  build:
    docker:
      - image: centos:7.7
    working_directory: ~/build

    steps:
      - checkout
      - run: |
        sudo yum install -y epel-release
        sudo yum install -y \
            patchelf \
            binutils \
            curl-devel \
            openssl-devel \
            file \
            which \
            rsync \
            tar \
            cmake3
            gcc \
            glibc-devel
      - run: |
            git clone https://github.com/jhunkeler/reloc
            mkdir -p reloc/build
            pushd reloc/build
            cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
            make install
            popd
            rm -rf reloc
      - run: |
            mkdir build
            cd build
            cmake -DCMAKE_INSTALL_PREFIX=/opt/spm -DCMAKE_BUILD_TYPE=Release ..
            make
      - run: |
            ctest -V
      - run: |
            make install



