version: 2.1

jobs:
  build-centos7:
    docker:
      - image: centos:7

    environment:
      TEST_RESULTS: /tmp/test-results
      MALLOC_CHECK_: 1

    working_directory: ~/build

    steps:
      - run:
          name: "Prepare"
          command: |
            yum install -y epel-release
            yum install -y git

      - checkout

      - run:
          name: "Initialize"
          command: |
            .circleci/init.sh

      - run:
          name: "Install reloc"
          command: |
            .circleci/install_reloc.sh

      - run:
          name: "Install spm"
          command: |
            .circleci/install_spm.sh

      - run:
          name: "Run tests"
          command: |
            .circleci/test_spm.sh

      - store_test_results:
          path: /tmp/test-results

  build-macos:
    macos:
      xcode: 11.4.0

    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      DYLD_INSERT_LIBRARIES: /usr/lib/libgmalloc.dylib
      TEST_RESULTS: /tmp/test-results
      PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig

    steps:
      - checkout

      - run:
          name: "Initialize"
          command: |
            .circleci/init.sh

      - run:
          name: "Install reloc"
          command: |
            .circleci/install_reloc.sh

      - run:
          name: "Install spm"
          command: |
            .circleci/install_spm.sh

      - run:
          name: "Run tests"
          command: |
            .circleci/test_spm.sh

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-centos7
      - build-macos

