# bump
version: 2.1
executors:
  centos-executor:
    docker:
      - image: centos:7
    environment:
      - MALLOC_CHECK_: 1
    working_directory: ~/build

jobs:
  spm:
    executor: centos-executor
    steps:
      - name: "Install dependencies"
        run: |
          .circleci/init.sh

      - name: "Install reloc"
        run: |
          .circleci/install_reloc.sh

      - checkout

      - name: "Install spm"
        run: |
          .circleci/install_spm.sh

      - name: "Run tests"
        run: |
          .circleci/test_spm.sh
