version: 2.1

jobs:
  build:
    docker:
      - image: centos:7

    environment:
      MALLOC_CHECK_: 1

    working_directory: ~/build

    steps:
      - run:
          name: "Install dependencies"
          command: |
            .circleci/init.sh

      - run:
          name: "Install reloc"
          command: |
            .circleci/install_reloc.sh

      - checkout

      - run:
          name: "Install spm"
          command: |
            .circleci/install_spm.sh

      - run:
          name: "Run tests"
          command: |
            .circleci/test_spm.sh
