# bump
version: 2.1
jobs:
  build:
    docker:
      - image: centos:7

    working_directory: ~/build

    steps:
      - run: |
            yum install -y epel-release
            yum install -y git make patchelf binutils curl-devel openssl-devel file which rsync tar cmake3 gcc glibc-devel

      - checkout

      - run: |
            git clone https://github.com/jhunkeler/reloc
            mkdir -p reloc/build
            pushd reloc/build
            cmake3 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
            make install
            popd
            rm -rf reloc
      - run: |
            mkdir build
            cd build
            cmake3 -DCMAKE_INSTALL_PREFIX=/opt/spm -DCMAKE_BUILD_TYPE=Release ..
            make
      - run: |
            ctest3 -V
      - run: |
            make install



