/**
 * @file package.h
 */
#ifndef SPM_PACKAGE_H
#define SPM_PACKAGE_H

#define SPM_PACKAGE_MIN_DELIM 2
#define SPM_PACKAGE_EXTENSION ".tar.gz"
#define SPM_PACKAGE_MEMBER_SIZE 0xff
#define SPM_PACKAGE_MEMBER_ORIGIN_SIZE PATH_MAX
#define SPM_PACKAGE_MEMBER_SEPARATOR '-'
#define SPM_PACKAGE_MEMBER_SEPARATOR_PLACEHOLD '*'
#define SPM_PACKAGE_HEADER_FILELIST "# SPM PACKAGE FILE LIST"
#define SPM_PACKAGE_HEADER_DESCRIPTOR "# SPM PACKAGE DESCRIPTOR"

#endif //SPM_PACKAGE_H
