name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo apt-get -y update \
        && sudo apt-get -y install build-essential cmake libssl-dev libcurl4-openssl-dev patchelf \
        && git clone https://github.com/jhunkeler/reloc \
        && pushd reloc && cmake . && sudo make install && popd 
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
    - name: smoketest
      working-directory: build
      run: src/spm --list
